function callLectoraVariables() {
	var LectoralatestWindows = 'Windows NT 10';
	var LectoralatestChromeBrowser = 'Chrome';
	var LectoralatestChromeVersion = '100';
	var LectoralatestEdgeBrowser = 'Edg';
	var LectoralatestEdgeVersion = '100';
	var LectoraInternetExplorerBrowser = 'Trident';
	var LectoraFirefoxBrowser = 'Firefox';
	var LectoraotherWin10BrowserWindows1 = 'Chrome';
	var LectoraotherWin10BrowserWindows2 = 'Edg';
	var LectoraotherWin10BrowserWindows3 = 'Trident';
	var LectoraotherWin10BrowserWindows4 = 'Firefox';
	var LectoraoldWindowsWindows = 'Windows';
	var LectoraoldWindowsVersion = 'NT 10';
	var LectoramacOSiPadVersion = 'OS X';
	var LectoramacOSMont = 'OS X 12';
	var LectoramacOSMontSafBrowser = 'Safari';
	var LectoramacOSMontOthBrowser1 = 'Safari';
	var LectoramacOSMontOthBrowser2 = 'Chrome';
	var LectoraoldMacOSMac = 'OS X';
	var LectoraoldMacOSVersion = '12';
	var LectoraiPad = 'iPad';
	var LectoraiPadVersion = 'OS 15';
	var LectoraiPad15SafBrowser = 'Safari';
	var LectoraiPad15ChrBrowser = 'CriOS';
	var LectoraiPad15OthBrowser1 = 'Safari';
	var LectoraiPad15OthBrowser2 = 'CriOS';
	var LectoraiPadNot15Version = '15';
	var LectoraiPadProVersion = 'iPad Pro';
	var LectoraiPhoneVersion = 'iPhone';
	var LectoraAndroid11 = 'Android 11';
	var LectoraAndroid = 'Android';
	var LectoraAndroid11TabPhoneChrome = 'Chrome';
	var LectoralinuxLinux = 'Linux';
	var LectoralinuxAndroid = 'Android';
	var LectoraChromebookdevice = 'CriOS';
};
callLectoraVariables();